title: Oren Shapira # your name (or website title) here
logo: "/images/Oren Shapira.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  About myself: 9+ years as a Data and Informatics analyst in the healthcare sector. 
  <br><br>
  Currently wrapping up a MS degree in Applied Data Analytics at Boston University.
  <br><br>
  Check out my Data Science and Machine Learning Projects on this page!
  <br><br>
  <a href="https://www.linkedin.com/in/oren-shapira-4a222617//">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://github.com/omshapira//">View My Github Portfolio</a> 
  

